services:
  fastapi-blue:
    container_name: main-fastapi-blue
    image: ${FASTAPI_BLUE_IMAGE}:${TAG_BLUE}
    networks:
      - main-protostar
    env_file: .env
    environment:
      - APP_ENV=production
    restart: unless-stopped

  fastapi-green:
    container_name: main-fastapi-green
    image: ${FASTAPI_GREEN_IMAGE}:${TAG_GREEN}
    networks:
      - main-protostar
    env_file: .env
    environment:
      - APP_ENV=production
    restart: unless-stopped

networks:
  main-protostar:
    external: true
    name: main-protostar